### ISSUE TITLE
[Question / Non-Issue] New release with the latest changes?

### ISSUE THREAD

**Issue by osteffenrh** [kupiakos/open-enum#18]
Hi @kupiakos,

Sorry for opening an issue for this, but I don't see any other way of reaching out.

I wanted to ask if it would be possible to publish a new release to crates.io, including
the latest fix around the missing License file.
I am packaging this crate for Fedora and the tools keep complaining about it.
Patching this downstream looks somewhat messy...

Thanks,
 Oliver

**Comment by kupiakos** [comment]
Hi @osteffenrh,

No need to apologize; this is the appropriate venue for such a request. I've [published v0.5.1](https://crates.io/crates/open-enum/0.5.1) for both the main and -derive crate to crates.io, the only difference being the LICENSE file.

**Comment by osteffenrh** [comment]
Thanks a lot! :-)
